language: node_js
node_js:
  - "12.14.1"

addons:
  chrome: stable

jobs:
  include:
    - stage: lint
      script: lerna run lint
    - stage: build
      script: lerna run build
    - stage: test
      script: lerna run test:ci
    - stage: e2e
      script: lerna run e2e
